package eu.ecotopia.backend.tile.model;

public enum TileType {
    HEALTHY_FOREST, SICK_FOREST,
    CLEAN_RIVER, POLLUTED_RIVER,
    FARMLAND, DEAD_FARMLAND,
    WASTELAND,
    FACTORY, CLEAN_FACTORY,
    OIL_REFINERY, COAL_PLANT,
    RESIDENTIAL, CITY_CENTER,
    RESEARCH_CENTER,
    SOLAR_FIELD, FUSION_REACTOR
}
