package eu.ecotopia.backend.speech.model;

/**
 * Represents a single citizen reaction generated by the AI.
 * Used for JSON deserialization of AI responses.
 */
public record AiCitizenReaction(
        String citizenName,
        String dialogue,
        String tone,
        int approvalDelta
) {
}
